name: isolator
description: Isolator is a package, which offer to you a simple way for creating two-component states with isolated part and frontend part of any kind (BLoC, MobX, ChangeNotifier and many others)
version: 0.0.1

repository: https://github.com/alphamikle/isolator
homepage: https://github.com/alphamikle/isolator

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.24
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
