name: isolator
description: Isolator is a package, which offer to you a simple way for creating two-component states with isolated part and frontend part of any kind - BLoC, MobX, ChangeNotifier and others
version: 2.0.8

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
